apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-gateway-book
  namespace: gateway-example
spec:
  selector:
    matchLabels:
      app: spring-gateway-book-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-gateway-book-app
    spec:
      containers:
      - name: spring-gateway-book-app
        image: basaki/spring-gateway-book:1.0.0
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: deployed
        ports:
          - containerPort: 8080
            name: http
          - containerPort: 8081
            name: management
        volumeMounts:
          - name: spring-gateway-book-config
            mountPath: /usr/local/example/config/env
            subPath: env
            readOnly: true
          - name: spring-gateway-book-config
            mountPath: /usr/local/example/config/application-deployed.yml
            subPath: application-deployed.yml # application yml
            readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 1
      volumes:
        - name: spring-gateway-book-config
          configMap:
            name: spring-gateway-book-config